Fix build on Java 8
When I tried to build mongo-hadoop on java 8 I had errors likes:

```
MongoConfigUtil.java:173: error: self-closing element not allowed
     * <p/>
       ^
```

It seems that for JDK 8 it has been decided that tags like <br /> and <p /> should generate errors, because they are invalid (strict) HTML 4.

Good discussion about this on JDK mail list: http://mail.openjdk.java.net/pipermail/core-libs-dev/2013-July/019261.html